<?php

namespace AppBundle\Repository;

/**
 * ProductTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductTagRepository extends \Doctrine\ORM\EntityRepository
{
}
