product_index:
    path:     /
    defaults: { _controller: "AppBundle:Product:index" }
    methods:  GET

product_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Product:show" }
    methods:  GET



