app_product_list:
    path: /
    defaults: { _controller: AppBundle:Product:list, _format: json }
    methods: [GET]

app_product_image_upload:
    path: /image
    defaults: { _controller: AppBundle:Product:upload }
    methods: [POST, GET]