app_product:
    resource: "@AppBundle/Resources/config/routing/product.yml"
    prefix:   /product

app_product_list:
    path: /
    defaults: { _controller: AppBundle:Product:list, _format: json }
    methods: [GET]

app_product_image_upload:
    path: /image
    defaults: { _controller: AppBundle:Product:upload, _format: json }
    methods: [POST]

app_product_image_upload_form:
    path: /image
    defaults: { _controller: AppBundle:Product:upload }
    methods: [GET]

app_product_image_tag_upload:
    path: /tag
    defaults: { _controller: AppBundle:Product:tag, _format: json }
    methods: [POST]

app_product_image_tag_upload_form:
    path: /tag
    defaults: { _controller: AppBundle:Product:tag }
    methods: [GET]